// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcRKUGe6OXWfQMcPUnLDllvmNKo94wQGA',
    appId: '1:442560291726:web:aedbaf4235cb8368e2badf',
    messagingSenderId: '442560291726',
    projectId: 'ors-chat-4b9a2',
    authDomain: 'ors-chat-4b9a2.firebaseapp.com',
    storageBucket: 'ors-chat-4b9a2.appspot.com',
    measurementId: 'G-8SWP4TH572',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbb22UAglFn8pXXmRS5-bL8_YIvSmZXeA',
    appId: '1:442560291726:android:7b6c753564154461e2badf',
    messagingSenderId: '442560291726',
    projectId: 'ors-chat-4b9a2',
    storageBucket: 'ors-chat-4b9a2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5XTXYbV5-XsjF_NLJlQz-sy4zHjdo0K8',
    appId: '1:442560291726:ios:eab1317667033d43e2badf',
    messagingSenderId: '442560291726',
    projectId: 'ors-chat-4b9a2',
    storageBucket: 'ors-chat-4b9a2.appspot.com',
    iosClientId: '442560291726-bajrn8o2bipe2h0n5a5soukfasm6u4vb.apps.googleusercontent.com',
    iosBundleId: 'orschat.talk4fun.net.orschat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5XTXYbV5-XsjF_NLJlQz-sy4zHjdo0K8',
    appId: '1:442560291726:ios:eab1317667033d43e2badf',
    messagingSenderId: '442560291726',
    projectId: 'ors-chat-4b9a2',
    storageBucket: 'ors-chat-4b9a2.appspot.com',
    iosClientId: '442560291726-bajrn8o2bipe2h0n5a5soukfasm6u4vb.apps.googleusercontent.com',
    iosBundleId: 'orschat.talk4fun.net.orschat',
  );
}
